name: ml3
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - cython
  - ipython
  - jupyter
  - jupyterlab
  - matplotlib
  - mlxtend
  - nodejs
  - numpy
  - pandas
  - python=3.8.6
  - scikit-learn
  - scipy
  - skrebate
  - tqdm
  - pip
  - pip:
    - nbmerge

